name: PluginManagerReloaded
version: 1.0.0
author: lvletei
authors: [obnoxint, Technius]
description: A plugin used for managing plugins
main: com.jadeningle.PluginManager.PluginManagerReloaded

commands:
    pluginmanager:
        description: PluginManager commands
        aliases: [plman, plm, pm]
permissions:
    pluginmanager.*:
        default: op
        description: Gives all PluginManager permissions
        children:
            pluginmanager.list: true
            pluginmanager.enable: true
            pluginmanager.disable: true
            pluginmanager.load: true
            pluginmanager.unload: true
            pluginmanager.reload: true
            pluginmanager.show: true
            pluginmanager.softreload: true
            pluginmanager.notify: true
    pluginmanager.list:
        default: false
    pluginmanager.enable:
        default: false
    pluginmanager.disable:
        default: false
    pluginmanager.load:
        default: false
    pluginmanager.unload:
        default: false
    pluginmanager.reload:
        default: false
    pluginmanager.show:
        default: false
    pluginmanager.softreload:
        default: false
    pluginmanager.notify:
        default: false
        